/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CardapioRouteImport } from './routes/cardapio'
import { Route as PedidoIndexRouteImport } from './routes/pedido.index'
import { Route as PedidoTokenRouteImport } from './routes/pedido.$token'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks/mercadopago'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardapioRoute = CardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIndexRoute = PedidoIndexRouteImport.update({
  id: '/pedido/',
  path: '/pedido/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoTokenRoute = PedidoTokenRouteImport.update({
  id: '/pedido/$token',
  path: '/pedido/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cardapio': typeof CardapioRoute
  '/pedido/$token': typeof PedidoTokenRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/pedido/': typeof PedidoIndexRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cardapio': typeof CardapioRoute
  '/pedido/$token': typeof PedidoTokenRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/pedido': typeof PedidoIndexRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cardapio': typeof CardapioRoute
  '/pedido/$token': typeof PedidoTokenRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/pedido/': typeof PedidoIndexRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cardapio'
    | '/pedido/$token'
    | '/produto/$slug'
    | '/pedido/'
    | '/api/public/webhooks/mercadopago'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cardapio'
    | '/pedido/$token'
    | '/produto/$slug'
    | '/pedido'
    | '/api/public/webhooks/mercadopago'
  id:
    | '__root__'
    | '/'
    | '/cardapio'
    | '/pedido/$token'
    | '/produto/$slug'
    | '/pedido/'
    | '/api/public/webhooks/mercadopago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardapioRoute: typeof CardapioRoute
  PedidoTokenRoute: typeof PedidoTokenRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  PedidoIndexRoute: typeof PedidoIndexRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardapio': {
      id: '/cardapio'
      path: '/cardapio'
      fullPath: '/cardapio'
      preLoaderRoute: typeof CardapioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/': {
      id: '/pedido/'
      path: '/pedido'
      fullPath: '/pedido/'
      preLoaderRoute: typeof PedidoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$token': {
      id: '/pedido/$token'
      path: '/pedido/$token'
      fullPath: '/pedido/$token'
      preLoaderRoute: typeof PedidoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardapioRoute: CardapioRoute,
  PedidoTokenRoute: PedidoTokenRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  PedidoIndexRoute: PedidoIndexRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
